files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/strings.xml
  - source: /docs/res/values/strings.xml
    translation: /docs/res/values-%two_letters_code%/strings.xml
